{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "customer.secretName" . }}
  labels:
    {{- include "customer.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.storeName }}
  target:
    name: {{ include "customer.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ required "externalSecret.remoteSecretName is required" .Values.externalSecret.remoteSecretName }}
        property: password
    {{- with .Values.externalSecret.oidcClientSecretName }}
    - secretKey: IDENTITY_ADMIN_CLIENT_SECRET
      remoteRef:
        key: {{ . }}
        property: client_secret
    {{- end }}
{{- end }}
